platform :ios, '13.0'

install! 'cocoapods', :disable_input_output_paths => true
use_frameworks! :linkage => :static
use_modular_headers!

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', 'Debug' => :debug, 'Profile' => :release, 'Release' => :release

def flutter_root
  flutter_path = File.realpath(`which flutter`.strip)
  raise "Flutter command not found. Make sure flutter is on your PATH." if flutter_path.empty?
  File.expand_path(File.join(File.dirname(flutter_path), '..'))
end

require File.expand_path(File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb'))

flutter_application_path = File.expand_path('..', __FILE__)

load File.join(flutter_application_path, '.flutter-plugins-dependencies') if File.exist?(File.join(flutter_application_path, '.flutter-plugins-dependencies'))

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
