name: android
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.2
  path_provider: ^2.1.5
  printing: ^5.13.4
  pdf: ^3.11.1
  file_saver: ^0.3.1
  url_launcher: ^6.3.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/group_20.png
    - assets/images/group_20_menu.png
    - assets/images/group_21.png
    - assets/images/group_23.png
    - assets/images/check.png




